# Generated by Django 5.2.4 on 2025-10-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staff_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_meter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFromTheRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='operator',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='code',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
