# Generated by Django 5.2.4 on 2025-10-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_material_typeofservice_workfromtherole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('customer_pincode', models.CharField(max_length=10)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('customer_alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('work_got_time', models.DateTimeField()),
                ('work_closing_time', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='core.operator')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='core.typeofservice')),
                ('work_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='core.workfromtherole')),
            ],
        ),
    ]
