# Generated by Django 5.2.4 on 2025-10-08 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_technician_workstb'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Technician', 'Technician')], max_length=20)),
                ('collection_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_to_company_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_work', models.IntegerField(default=0)),
                ('assigned_work', models.IntegerField(default=0)),
                ('completed_work', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='workstb',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='workstb',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_works', to='core.user'),
        ),
        migrations.AddField(
            model_name='workstb',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_works', to='core.user'),
        ),
    ]
