# Generated by Django 5.2.4 on 2025-10-08 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_workstb_status_workstb_assigned_technician_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='paid_to_company_amount',
            new_name='paid_to_company',
        ),
        migrations.RenameField(
            model_name='workstb',
            old_name='customer_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='workstb',
            old_name='customer_alternate_mobile',
            new_name='alternate_no',
        ),
        migrations.RenameField(
            model_name='workstb',
            old_name='customer_mobile',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='workstb',
            old_name='customer_pincode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='workstb',
            old_name='customer_whatsapp',
            new_name='wp_no',
        ),
        migrations.RemoveField(
            model_name='workstb',
            name='service_type',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='workstb',
            name='type_of_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.typeofservice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('technician', 'Technician')], default='technician', max_length=20),
        ),
        migrations.AlterField(
            model_name='workstb',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workstb',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_work', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstb',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator'),
        ),
        migrations.AlterField(
            model_name='workstb',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_work', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstb',
            name='work_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.workfromtherole'),
            preserve_default=False,
        ),
    ]
