# Generated by Django 5.2.4 on 2025-10-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_paid_to_company_amount_user_paid_to_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_remark', models.TextField(blank=True, null=True)),
                ('used_materials', models.JSONField(blank=True, default=list)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='core.workstb')),
            ],
        ),
    ]
