# Generated by Django 5.2.4 on 2025-10-09 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
