# Generated by Django 5.2.4 on 2025-10-09 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_address_user_alternate_no_user_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='undersupervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians_under', to=settings.AUTH_USER_MODEL),
        ),
    ]
