# Generated by Django 5.2.4 on 2025-10-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_collectiontransfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
