# Generated by Django 5.2.4 on 2025-10-19 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_supervisorcategory_alter_user_role_fos_retailer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='undersupervisor',
        ),
        migrations.AddField(
            model_name='user',
            name='fos_links',
            field=models.ManyToManyField(blank=True, related_name='retailers_under', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_under', to=settings.AUTH_USER_MODEL),
        ),
    ]
