# Generated by Django 5.2.4 on 2025-10-19 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_user_undersupervisor_user_fos_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FosOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fos', models.ForeignKey(limit_choices_to={'role': 'fos'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
            options={
                'unique_together': {('fos', 'operator')},
            },
        ),
    ]
