# Generated by Django 5.2.4 on 2025-10-19 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fosoperator'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerFosMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fos', models.ForeignKey(limit_choices_to={'role': 'fos'}, on_delete=django.db.models.deletion.CASCADE, related_name='fos_retailer_maps', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(limit_choices_to={'role': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_fos_maps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FosOperatorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fos', models.ForeignKey(limit_choices_to={'role': 'fos'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
            options={
                'unique_together': {('fos', 'operator')},
            },
        ),
    ]
