# Generated by Django 5.2.4 on 2025-10-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_retailerfosmap_fosoperatormap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FosOperator',
        ),
    ]
