# Generated by Django 5.2.4 on 2025-10-20 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_fosoperator'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('partner_id', models.CharField(max_length=50)),
                ('partner_name', models.CharField(max_length=200)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_without_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
