# Generated by Django 5.2.4 on 2025-10-21 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product_productstock_purchase_purchaseitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('area_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pincode'],
            },
        ),
        migrations.CreateModel(
            name='PincodeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pincode_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.pincode')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_pincodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['supervisor__name', 'pincode__pincode'],
                'unique_together': {('supervisor', 'pincode')},
            },
        ),
    ]
