# Generated by Django 5.2.4 on 2025-10-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pincode_pincodeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='technician_type',
            field=models.CharField(blank=True, choices=[('own', 'Own Technician'), ('freelance', 'Freelance Technician')], max_length=20, null=True),
        ),
    ]
