# Generated by Django 5.2.4 on 2025-10-30 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_product_price_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__name', 'product__name'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
