# Generated by Django 5.2.4 on 2025-10-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_userproductstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstb',
            name='category',
            field=models.CharField(choices=[('dth', 'DTH'), ('fiber', 'Air Fiber')], default='dth', max_length=10),
        ),
        migrations.AddField(
            model_name='workstb',
            name='dth_type',
            field=models.CharField(blank=True, choices=[('fullset', 'Full Set'), ('box', 'Box Only')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workstb',
            name='fiber_type',
            field=models.CharField(blank=True, choices=[('with_iptv', 'With IPTV'), ('without_iptv', 'Without IPTV')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workstb',
            name='fr_issue',
            field=models.CharField(blank=True, choices=[('box', 'Box Issue'), ('signal', 'Signal Issue')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workstb',
            name='job_type',
            field=models.CharField(choices=[('fr', 'Field Repair'), ('reinstallation', 'Reinstallation'), ('deinstallation', 'Deinstallation'), ('retrieval', 'Retrieval')], default='fr', max_length=20),
        ),
        migrations.AddField(
            model_name='workstb',
            name='kind',
            field=models.CharField(choices=[('service', 'Service'), ('installation', 'Installation')], default='service', max_length=20),
        ),
        migrations.AddField(
            model_name='workstb',
            name='warranty',
            field=models.CharField(choices=[('in', 'In Warranty'), ('out', 'Out of Warranty')], default='out', max_length=10),
        ),
    ]
