# Generated by Django 5.2.4 on 2025-11-01 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_workstb_category_workstb_dth_type_workstb_fiber_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='who_collected',
            field=models.ForeignKey(blank=True, help_text='Who collected the money from customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
