# Generated by Django 5.2.4 on 2025-11-01 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_workreport_who_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='productserial',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, help_text='User who currently has this serial in stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_serials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productserial',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Used', 'Used'), ('Defective', 'Defective'), ('Returned', 'Returned')], default='Available', help_text='Current status of this serial number', max_length=20),
        ),
        migrations.AddField(
            model_name='productserial',
            name='used_in_work',
            field=models.ForeignKey(blank=True, help_text='Work order where this serial was used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_serials', to='core.workstb'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='repair_type',
            field=models.CharField(blank=True, choices=[('Swapping', 'Swapping'), ('Field Repair', 'Field Repair'), ('Retrieval', 'Retrieval')], help_text='Type of repair work (only for repair service)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workreport',
            name='returned_product',
            field=models.ForeignKey(blank=True, help_text='Defective product returned by customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_in_works', to='core.product'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantity of returned product (for non-serialized)', max_digits=10),
        ),
        migrations.AddField(
            model_name='workreport',
            name='returned_serial',
            field=models.CharField(blank=True, help_text='Serial number of returned defective product', max_length=255, null=True),
        ),
    ]
