# Generated by Django 5.2.4 on 2025-11-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_productserial_assigned_to_user_productserial_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstb',
            name='closing_otp',
            field=models.CharField(blank=True, help_text='OTP sent to customer for work closing', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='workstb',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, help_text='When OTP was sent', null=True),
        ),
    ]
