# Generated by Django 5.2.4 on 2025-11-02 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_workstb_closing_otp_workstb_otp_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pending payment amount for freelancer work', max_digits=10),
        ),
        migrations.AddField(
            model_name='workreport',
            name='freelancer_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to be paid to freelancer technician for this work', max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='collection_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount collected from customers', max_digits=10),
        ),
        migrations.CreateModel(
            name='TechnicianPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_paid_at', models.DateTimeField(blank=True, help_text='When supervisor marked as paid', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When technician accepted payment', null=True)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_payments', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician', 'technician_type': 'freelance'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, help_text='Work order for which payment is being made', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_payments', to='core.workstb')),
            ],
        ),
    ]
