# Generated by Django 5.2.4 on 2025-11-02 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_user_payment_wallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstb',
            name='work_got_time',
        ),
        migrations.AddField(
            model_name='workstb',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workstb',
            name='work_deadline_time',
            field=models.DateTimeField(blank=True, help_text='Deadline to complete the work', null=True),
        ),
        migrations.AlterField(
            model_name='workstb',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Expired', 'Expired'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
