# Generated by Django 5.2.4 on 2025-11-04 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_ectransfer_simpurchase_simstock_simtransfer_ecstock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ectransfer',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='ectransfer',
            name='to_user',
        ),
        migrations.CreateModel(
            name='EcCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_level', models.CharField(choices=[('retailer_to_fos', 'Retailer → FOS'), ('fos_to_supervisor', 'FOS → Supervisor'), ('supervisor_to_admin', 'Supervisor → Admin')], max_length=30)),
                ('collection_amount', models.DecimalField(decimal_places=2, help_text='Amount collected', max_digits=12)),
                ('pending_before', models.DecimalField(decimal_places=2, help_text='Pending amount before collection', max_digits=12)),
                ('pending_after', models.DecimalField(decimal_places=2, help_text='Pending amount after collection', max_digits=12)),
                ('collection_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ec_collections_done', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_collections_given', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_collections_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Order ID from recharge system', max_length=50, unique=True)),
                ('order_date', models.DateField(help_text='Date of recharge order')),
                ('partner_id', models.CharField(help_text='Partner ID from system', max_length=50)),
                ('partner_name', models.CharField(help_text='Partner Name (Retailer name)', max_length=255)),
                ('transfer_amount', models.DecimalField(decimal_places=2, help_text='Total transfer amount', max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, help_text='Commission earned', max_digits=10)),
                ('amount_without_commission', models.DecimalField(decimal_places=2, help_text='Amount retailer owes to FOS', max_digits=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_type', models.CharField(choices=[('manual', 'Manual'), ('excel', 'Excel')], default='manual', max_length=20)),
                ('fos', models.ForeignKey(limit_choices_to={'role': 'fos'}, on_delete=django.db.models.deletion.CASCADE, related_name='ec_sales_fos', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_sales', to='core.operator')),
                ('retailer', models.ForeignKey(limit_choices_to={'role': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='ec_sales_retailer', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='ec_sales_supervisor', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ec_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount pending to pay FOS', max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, help_text='Total EC sales', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EcStock',
        ),
        migrations.DeleteModel(
            name='EcTransfer',
        ),
        migrations.AddIndex(
            model_name='ecsale',
            index=models.Index(fields=['order_id'], name='core_ecsale_order_i_153a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='ecsale',
            index=models.Index(fields=['operator', 'order_date'], name='core_ecsale_operato_e70f94_idx'),
        ),
        migrations.AddIndex(
            model_name='ecsale',
            index=models.Index(fields=['retailer'], name='core_ecsale_retaile_831dbd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retailerwallet',
            unique_together={('retailer', 'operator')},
        ),
    ]
