# Generated by Django 5.2.4 on 2025-11-05 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_ectransfer_from_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FosWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount collected from retailers, pending to supervisor', max_digits=12)),
                ('total_collected_from_retailers', models.DecimalField(decimal_places=2, default=0, help_text='Total EC collected from retailers', max_digits=12)),
                ('total_paid_to_supervisor', models.DecimalField(decimal_places=2, default=0, help_text='Total EC paid to supervisor', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fos_wallet', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
            options={
                'unique_together': {('fos', 'operator')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount collected from FOS, pending to admin', max_digits=12)),
                ('total_collected_from_fos', models.DecimalField(decimal_places=2, default=0, help_text='Total EC collected from FOS', max_digits=12)),
                ('total_paid_to_admin', models.DecimalField(decimal_places=2, default=0, help_text='Total EC paid to admin', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('supervisor', 'operator')},
            },
        ),
    ]
