# Generated by Django 5.2.8 on 2025-11-06 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_foswallet_supervisorwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_level', models.CharField(choices=[('retailer_to_fos', 'Retailer → FOS'), ('fos_to_supervisor', 'FOS → Supervisor'), ('supervisor_to_admin', 'Supervisor → Admin')], max_length=30)),
                ('collection_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pending_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pending_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_collections_made', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_collections_given', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_collections_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FosSimWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount collected from retailers, pending to supervisor', max_digits=12)),
                ('total_collected_from_retailers', models.DecimalField(decimal_places=2, default=0, help_text='Total amount collected from retailers', max_digits=12)),
                ('total_paid_to_supervisor', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid to supervisor', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fos_sim_wallet', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
            options={
                'unique_together': {('fos', 'operator')},
            },
        ),
        migrations.CreateModel(
            name='RetailerSimWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount owed to FOS for SIMs received', max_digits=12)),
                ('total_sims_received', models.IntegerField(default=0, help_text='Total SIMs received from FOS')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total value of SIMs received', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_sim_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('retailer', 'operator')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorSimWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount collected from FOS, pending to admin', max_digits=12)),
                ('total_collected_from_fos', models.DecimalField(decimal_places=2, default=0, help_text='Total amount collected from FOS', max_digits=12)),
                ('total_paid_to_admin', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid to admin', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_sim_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('supervisor', 'operator')},
            },
        ),
    ]
