# Generated by Django 5.2.8 on 2025-11-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_simcollection_fossimwallet_retailersimwallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simtransfer',
            name='batch_id',
            field=models.CharField(blank=True, help_text='Group transfers made together', max_length=100, null=True),
        ),
    ]
