# Generated by Django 5.2.8 on 2025-11-06 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_simtransfer_batch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandsetCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_level', models.CharField(choices=[('retailer_to_fos', 'Retailer → FOS'), ('fos_to_supervisor', 'FOS → Supervisor'), ('supervisor_to_admin', 'Supervisor → Admin')], max_length=30)),
                ('collection_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pending_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pending_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handset_collections_made', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handset_collections_given', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handset_collections_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandsetPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='HandsetStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('imei_number', models.CharField(blank=True, help_text='IMEI number if applicable', max_length=20, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('damaged', 'Damaged'), ('returned', 'Returned')], default='available', max_length=20)),
                ('sold_to_customer', models.CharField(blank=True, max_length=200, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handset_stock', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handsets', to='core.handsetpurchase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandsetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('transfer', 'Transfer'), ('return', 'Return')], default='transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('batch_id', models.CharField(blank=True, help_text='Group transfers made together', max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handset_transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('handset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.handsetstock')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handset_transfers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandsetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Handset type name (e.g., JioPhone Next)', max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Price at which handset is purchased', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price at which handset is sold', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handset_types', to='core.operator')),
            ],
            options={
                'ordering': ['operator', 'name'],
                'unique_together': {('operator', 'name')},
            },
        ),
        migrations.AddField(
            model_name='handsetstock',
            name='handset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.handsettype'),
        ),
        migrations.AddField(
            model_name='handsetpurchase',
            name='handset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.handsettype'),
        ),
        migrations.CreateModel(
            name='FosHandsetWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount pending to be paid to Supervisor', max_digits=12)),
                ('total_collected_from_retailers', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid_to_supervisor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fos_handset_wallet', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
            options={
                'ordering': ['fos', 'operator'],
                'unique_together': {('fos', 'operator')},
            },
        ),
        migrations.CreateModel(
            name='RetailerHandsetWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount pending to be paid to FOS', max_digits=12)),
                ('total_handsets_received', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total value of all handsets received', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_handset_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['retailer', 'operator'],
                'unique_together': {('retailer', 'operator')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorHandsetWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount pending to be paid to Admin', max_digits=12)),
                ('total_collected_from_fos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid_to_admin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_handset_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['supervisor', 'operator'],
                'unique_together': {('supervisor', 'operator')},
            },
        ),
    ]
